// automatically generated by the FlatBuffers compiler, do not modify

package packets

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ComponentWrapper struct {
	_tab flatbuffers.Table
}

func GetRootAsComponentWrapper(buf []byte, offset flatbuffers.UOffsetT) *ComponentWrapper {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ComponentWrapper{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ComponentWrapper) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ComponentWrapper) ComponentType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ComponentWrapper) MutateComponentType(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *ComponentWrapper) Component(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func ComponentWrapperStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ComponentWrapperAddComponentType(builder *flatbuffers.Builder, componentType byte) {
	builder.PrependByteSlot(0, componentType, 0)
}
func ComponentWrapperAddComponent(builder *flatbuffers.Builder, component flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(component), 0)
}
func ComponentWrapperEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
