// automatically generated by the FlatBuffers compiler, do not modify

package packets

const (
	ComponentNONE = 0
	ComponentShip = 1
)

var EnumNamesComponent = map[int]string{
	ComponentNONE:"NONE",
	ComponentShip:"Ship",
}

