// automatically generated by the FlatBuffers compiler, do not modify

package packets

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PacketWrapper struct {
	_tab flatbuffers.Table
}

func GetRootAsPacketWrapper(buf []byte, offset flatbuffers.UOffsetT) *PacketWrapper {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PacketWrapper{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PacketWrapper) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PacketWrapper) DataType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PacketWrapper) MutateDataType(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *PacketWrapper) Data(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func PacketWrapperStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PacketWrapperAddDataType(builder *flatbuffers.Builder, dataType byte) {
	builder.PrependByteSlot(0, dataType, 0)
}
func PacketWrapperAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(data), 0)
}
func PacketWrapperEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
