// automatically generated by the FlatBuffers compiler, do not modify

package packets

const (
	PacketNONE = 0
	PacketWorldSnapshot = 1
)

var EnumNamesPacket = map[int]string{
	PacketNONE:"NONE",
	PacketWorldSnapshot:"WorldSnapshot",
}

