// automatically generated by the FlatBuffers compiler, do not modify

package packets

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Ship struct {
	_tab flatbuffers.Table
}

func GetRootAsShip(buf []byte, offset flatbuffers.UOffsetT) *Ship {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Ship{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Ship) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Ship) Armed() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Ship) MutateArmed(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *Ship) Shielded() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Ship) MutateShielded(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func ShipStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ShipAddArmed(builder *flatbuffers.Builder, armed byte) {
	builder.PrependByteSlot(0, armed, 0)
}
func ShipAddShielded(builder *flatbuffers.Builder, shielded byte) {
	builder.PrependByteSlot(1, shielded, 0)
}
func ShipEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
